### ISSUE TITLE
Use 0 for all secondary mapping of the table

### ISSUE THREAD

**Issue by yookoala** [Cangjians/libcangjie#104]
Need to update dbbuilder to implement mechanism suggested by https://github.com/Cangjians/ibus-cangjie/issues/77#issuecomment-269938845 (solution B). The aim is to remove the disturbance of all non-standard mapping to the order in Quick input method and resolve https://github.com/Cangjians/ibus-cangjie/issues/77.

**Comment by bochecha** [comment]
I think we misunderstood each other when I asked to open a new issue for this, in #77.

What I meant was that we could fix #77 by adding 3 special cases like we have already for `氐`, and open a new issue to discuss a more general solution.

I see you went straight for the more general solution with #105, which is fine, but it makes this issue a bit pointless.

If we're not going to bother with the direct fix for #77 then this issue is a bit pointless. I'm sorry I made you do something pointless. 😞

**Comment by bochecha** [comment]
We have moved to Freedesktop: https://gitlab.freedesktop.org/cangjie/libcangjie

Please continue discussion there.
